language: java
jdk: oraclejdk8
services: docker
env: SPRING_PROFILES_ACTIVE=travis-ci
before_install:
  - nvm install 6
  - docker-compose up -d
script:
  - cd ui/
  - npm run travis-ci
  - cd ../
  - gradle clean build
after_script:
  - docker-compose kill
  - true & cat ui/*.log
cache.directories:
  - /var/lib/docker
  - $HOME/.gradle
  - $HOME/.m2
  - web/node_modules
  - .gradle
  - gradle
notifications.on_failure: change # always | never
